title: NPA Support
description: A hub for all things NPA Related
baseurl: "/"
url: "https://support.devclient.info"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: dark

remote_theme: just-the-docs/just-the-docs
